### ISSUE TITLE
Make zkVM inputs structure pattern more discoverable

### ISSUE THREAD

**Issue by tzerrell** [risc0/risc0#598] opened 2023-06-01 23:23 UTC
The factors example passes two concatenated inputs, which is not the recommended pattern. Instead, we recommend creating a structure of all the other inputs, as in most of our other examples. Add comments/documentation to make this clearer -- see further discussion here: https://github.com/risc0/risc0/pull/595#discussion_r1213723987

**Comment by pdg744** [comment] 2023-09-22 20:49
some discord confusion on this topic recently:

![Image](https://github.com/risc0/risc0/assets/15272444/874a2bba-31e9-4012-ae7e-7dbf40e0b82d)



![Image](https://github.com/risc0/risc0/assets/15272444/521f2e46-7c4e-4009-9f05-26845669c902)



![Image](https://github.com/risc0/risc0/assets/15272444/8e10f721-fb61-459a-8386-fe87ab9a76e7)

**Comment by flaub** [comment] 2023-10-07 20:04
Duplicate of #845

**Closed by flaub** 2023-10-07 20:04 UTC
Labels: documentation
