### ISSUE TITLE
RISC0 and  FHE

### ISSUE THREAD

**Issue by Guangguang888** [risc0/risc0#645] opened 2023-06-20 02:58 UTC
Has anyone successfully combined risc with a fully homomorphic encryption tool? I tried many fully homomorphic encryption tools, but without success.

**Comment by pdg744** [comment] 2023-06-20 14:12
This looks redundant with #607; is there a reason we want/need a second place for conversation about this?

**Comment by SchmErik** [comment] 2023-06-26 21:07
This seems to be a duplicate of #607 closing

**Closed by SchmErik** 2023-06-26 21:07 UTC
Labels: duplicate
