### ISSUE TITLE
Instruction Not Implemented

### ISSUE THREAD

**Issue by wangtsiao** [risc0/risc0#591] opened 2023-05-30 14:39 UTC
I am trying to run an evm inside the risc0.

```
cargo run -- --rpc-url http://127.0.0.1:8545 --tx-hash 0xad8ab52f0c378c7e750ccdf25cc0894b53eab5d5c3d018a1226c541469522b5f


   Compiling evm-methods v0.1.0 (/Users/tsiao/Desktop/windranger-lab/evm-risc0/methods)
methods-guest: Starting build for riscv32im-risc0-zkvm-elfods(build)                                                                                                                           
methods-guest:     Updating crates.io index
methods-guest:     Finished release [optimized] target(s) in 2.41s
   Compiling evm v0.1.0 (/Users/tsiao/Desktop/windranger-lab/evm-risc0)
    Finished dev [unoptimized + debuginfo] target(s) in 13.74s
     Running `target/debug/evm --rpc-url 'http://127.0.0.1:8545' --tx-hash 0xad8ab52f0c378c7e750ccdf25cc0894b53eab5d5c3d018a1226c541469522b5f`
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NotSupported', ./src/guest/env.rs:258:54
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: illegal instruction at 0x712a2e8: 11000000000000000001000001110011 (1110011, 001, 00000, 1100000)', src/main.rs:99:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here I found `illegal instruction at 0x712a2e8: 11000000000000000001000001110011 (1110011, 001, 00000, 1100000)`, where the `1110011` in risc opcode [table](https://five-embeddev.com/riscv-isa-manual/latest/instr-table.html) is `ECALL`.

Did risc0 implement `ECALL`?

**Comment by mothran** [comment] 2023-05-30 16:04
Yes we use ECALL for all the host-guest communication, The `NotSupported` error is actually related to the serde serialize/deserialize between the host and guest: https://github.com/risc0/risc0/blob/7c529b64006382d06024ca5862297b18a77a895c/risc0/zkvm/src/serde/err.rs#L50

You might wanna inspect how your data is moving between the host -> guest, So check that your add_input() and env::read() match existing examples.

**Comment by wangtsiao** [comment] 2023-05-31 04:58
@mothran Thanks.

I copied the evm example from risc0, then I copied `rust-toolchain.toml`, `examples/Cargo.toml`.
And replace `risc0-zkvm`, `risc0-build` to version 0.15.1, the error still happened.

For reproduce the error, here is the [repo](https://github.com/wangtsiao/zkevm-risc0/tree/2ea8a4eb1a0c45bf5eaf4d87e6e99dc7e2dd4e57).

The command is as below
```
cargo build --release
RUST_LOG=info ./target/release/evm  --rpc-url https://rpc.flashbots.net/ --tx-hash 0x671a3b40ecb7d51b209e68392df2d38c098aae03febd3a88be0f1fa77725bbd7 --chain-id 1
```

**Comment by flaub** [comment] 2023-07-18 05:48
I was not able to reproduce this issue. I made a slight modification to your repository to get it to build. I added this to `methods/guest/Cargo.toml`:

```
[patch.crates-io]
radium = { git = 'https://github.com/ferrilab/radium.git', rev = "723bed5" }
```

And then I ran:
```
cd methods/guest
cargo update
```

I'll close this issue for now, but please re-open if it's still an issue for you.

**Closed by flaub** 2023-07-18 05:48 UTC
Labels: bug
