### ISSUE TITLE
Status of a toy solidity verifier?

### ISSUE THREAD

**Issue by SilentCicero** [risc0/risc0#702] opened 2023-07-16 08:49 UTC
What is the status of a toy solidity verifier for Risc0?

**Comment by flaub** [comment] 2023-07-18 04:08
Duplicate of #270 

We will be announcing https://dev.risczero.com/bonsai soon which provides the ability to generate a groth16 proof which can be verified in solidity. See this example: https://github.com/risc0/risc0/tree/main/bonsai/examples/governance

**Closed by flaub** 2023-07-18 04:08 UTC
