### ISSUE TITLE
[Feature] env::log sent to stdout, making it difficult to parse env::write's output

### ISSUE THREAD

**Issue by jswalens** [risc0/risc0#1305] opened 2024-01-09 15:52 UTC
## Feature
Since #1115, the output of `env::log` is also sent to stdout; to allow it to be read from the host. However, this means it gets mixed with the output written using `env::write()`, making it difficult to parse the latter. It'd be better if there was a way to distinguish the messages written to the log from the secret values written using `env::write()`.

## Motivation
If you write a program that uses `env::log` (maybe only during development) and `env::write` (to output secret values), it becomes very difficult to parse the values written using `env::write` in the host code. Ideally, I'd like to do something similar to [the voting machine example](https://github.com/risc0/risc0/blob/ddedd1815791e823d6af05b20e9dc2cb278119ef/examples/voting-machine/src/lib.rs#L95C17-L95C17), where the value is simply converted using `from_slice`. However, my stdout contains some logging messages before and after the actual value, and the length of those messages can change.

## Implementation
An idea is to send the output to `env::log` to stderr. Hence, stdout would only contain values the developer wrote using `env::write`, while stderr would contain 'debugging info'. Alternatively, the log could be a separate output from stdout and stderr.

**Comment by austinabell** [comment] 2024-01-09 16:23
related to https://github.com/risc0/risc0/issues/1038

**Comment by SchmErik** [comment] 2024-01-09 19:51
I'm going to close this as duplicate of #1038 so let's move the discussion to that issue.

@jswalens we'll be implementing the idea in #1038 shortly. In the meantime could you give feedback the idea proposed in #1038?

**Closed by SchmErik** 2024-01-09 19:51 UTC
Labels: enhancement
