### ISSUE TITLE
cannot find cuda installation

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1022] opened 2023-10-23 05:42 UTC
thread 'main' panicked at /home/cj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/find_cuda_helper-0.2.0/src/lib.rs:12:13:
  Could not find a cuda installation

**Comment by GopherJ** [comment] 2023-10-23 05:44
I have nvidia-cuda-toolkit and nvidia-driver-535 installed

**Comment by flaub** [comment] 2024-07-16 00:23
This might just be that the PATH needs to include `/usr/local/cuda/bin`.

**Comment by sgaure** [comment] 2024-09-16 11:20
Since I just struggled with this problem. 

It turns out that `find_cuda_helper` looks in `/opt/cuda` and `/usr/local/cuda` for `include/cuda.h`. However, my cuda is in `/usr`, so a `ln -s /usr /usr/local/cuda` did the trick.

**Comment by pdg744** [comment] 2024-11-12 15:22
i'm going to close this because there's not enough information included to reproduce your error. 

@GopherJ -- if you're still looking for support on this, please re-open with more information. we have issue templates here to help with that: https://github.com/risc0/risc0/issues/new/choose

**Closed by pdg744** 2024-11-12 15:22 UTC
Labels: bug
