### ISSUE TITLE
Composition fails to resolve assumption in the client/server API

### ISSUE THREAD

**Issue by rlukata** [risc0/risc0#1236] opened 2023-12-15 00:20 UTC
## Report
Composition fails with `value: sys_verify_integrity: failed to resolve journal_digest and image_id` when used with client/server API.

## Steps to Reproduce
1. Cargo.toml
```
risc0-zkvm = { workspace = true, features = ["client"] }
```
2. In the host:
```
let env = ExecutorEnv::builder()
        .add_assumption(receipt.clone().into())
        .write(&compute_image_id(METHOD_NAME_ELF)?)?
        .write(&receipt.journal.bytes)?
        .build()
        .unwrap();
let exec = default_executor();
let session = exec.execute(env, METHOD_NAME_ELF).unwrap();
```
3. In the guest:
```
let image_id: Digest = env::read();
let journal: Vec<u8> = env::read();
env::verify(image_id, &journal).unwrap();
```

## Expected behavior
The verify should pass.

## Your Environment
- risc0-zkvm version: 0.20.1 alpha
- Rust version: 1.72.1
- Platform/OS: M2 MacOS

**Comment by nategraf** [comment] 2023-12-15 00:38
I've confirmed that I forgot to add assumptions to the protobuf definition of `ExecutorEnv` and so assumptions are not transferred from client to server 🤦‍♂️ . https://github.com/risc0/risc0/blob/05f46ef83d7be3bd209070e67b57a5b45b56bfb1/risc0/zkvm/src/host/api/client.rs#L326-L347

Working on adding assumptions to the protobuf types and fixing this now

**Comment by nategraf** [comment] 2023-12-15 18:51
Deleted the "[Enhancement]" from the tittle since we have tags to indicate what type of issue this is

**Closed** 2023-12-22 02:04 UTC
Labels: enhancement
