### ISSUE TITLE
Make ELF binaries build deterministically 

### ISSUE THREAD

**Issue by jbruestle** [risc0/risc0#116] opened 2022-05-20 21:00 UTC
Currently when Cargo builds the guest methods, the resulting ELF files are not built deterministically (don't know why) resulting in incompatible method IDs.  Technically only the 'loadable' part of the ELF needs to be deterministic.

**Comment by shkoo** [comment] 2022-06-10 20:07
rust-lang/cargo#10746

**Comment by shkoo** [comment] 2022-06-15 04:47
Reopening for now, since std support (#148) requires a host spec file again.

If that cargo pull request gets merged that should fix this issue (but we'll want to add a cargo version check and warn if it's too old).  The other option is to build our own toolchain including cargo, and that's a bigger project.

**Comment by flaub** [comment] 2023-01-25 15:19
Found some other related issues:
https://github.com/rust-lang/rust/issues/75362
https://github.com/rust-lang/rust/issues/102299

Looks like we could try to use:
```
RUSTFLAGS="--remap-path-prefix=$HOME=/remap-home --remap-path-prefix=$PWD=/remap-pwd"
```

**Comment by flaub** [comment] 2023-01-25 15:26
https://github.com/rust-lang/rust/issues/98185
https://github.com/rust-lang/rust/labels/A-reproducibility

**Comment by flaub** [comment] 2023-01-25 15:36
https://github.com/rust-lang/rust/issues/34902

NEAR also uses a docker image: https://github.com/near/near-sdk-rs/issues/151

**Comment by Pernick** [comment] 2023-04-05 07:45
This also affects builds where multiple members of the workspace have guest methods as a dependency and using its image id for verifying https://github.com/RBFLabs/risc0-id-mismatch

**Comment by SchmErik** [comment] 2023-05-11 17:51
Here are several code changes that we've added in our tests which are likely due to nondeterministic binaries:

https://github.com/risc0/risc0/pull/553/files#diff-46a860afd43fe55f5e7442917718a4a5357fb4a76b2169d98c8c885158af8e2dR467

The `% 1094` was added because the different instructions could be laid out on page boundaries in certain situations and so when you execute the next instruction, it could cause a page-in. If the build were to be deterministic the difference between cycles would equate to a single value rather than `% 1094` which indicates multiples of the page-in cycle count.

We also increased the segment's power of 2 limit for the continuations test:
https://github.com/risc0/risc0/commit/a0f8ce3aa88df84d7a5613b2fa58c16a6a61d224#diff-86c5437677f80d40396200163171134d15dc3e6eb257f74c37f382c39da52697R207

This test results in either 7 or 8 segments depending on various commits and have caused headaches in the CI. What is happening is that the multitest binary is different on each commit and causes issues in where the segment split happens. It's as if the executor execution is "teetering" between 7 and 8 depending on the binary.

When we figure out the solution to build our guest code deterministically, we need to revert these tests so they're using their original values/conditions for the test.

**Comment by SchmErik** [comment] 2023-05-12 19:03
I've been looking at issues on github about reproducible builds and I wanted to add some observations...

When I build multitest on different commits, I get different values for `MULTI_TEST_ELF.len()` I'm not sure how this change happens but the length seems to increase the more code we add to the repo. There are a few claims that the rust builds aren't reproducible because the panic handler's contain relative paths. While this is true, I believe that this only a small part of the problem. We saw that in linux-cpu, we had a failure on the "trace" test. This was likely because the binary's instruction was laid out right on the page boundary and hit a page fault which incurred an additional 1094 cycles. I think this is evidence that the builds change with the code on the repo.

So here are some questions that I want to dive into:

How do code changes in the repo affect the multitest binary?
What's causing the increase in the size of the binary? How does the binary change? Is the increase in size confined to the binary?

I'll write scripts to run builds on each commit since continuations landed

**Closed** 2023-08-16 16:36 UTC
Labels: bug
