### ISSUE TITLE
[BUG] Bump v0.20.1 v0.21 release build fails on x86 `error: failed to load bitcode of module`

### ISSUE THREAD

**Issue by nuke-web3** [risc0/risc0#1914] opened 2024-05-31 18:17 UTC
## Bug Report

:eyes:  See [this post on discord](https://discord.com/channels/953703904086994974/1246071524905979956) for more details that @DefiCake ran into.

> these are the lines I change in the `Cargo.toml`:
> 
> Works (what I had before) (it worked with an old version of the toolchain and after upgrading the toolchain):
> risc0-build = { version = "0.20.1" }
> risc0-zkvm = { version = "0.20.1", default-features = false }
> 
> 
> Does not work (upgrade to 0.21) (it did not work either before or after updating the toolchain): 
> risc0-build = { version = "0.21.0" }
> risc0-zkvm = { version = "0.21.0", default-features = false }
> as Nuke said I might have to upgrade some other packages like the bonsai sdk... I did not try that yet. But I am not sure if it will have any effect given that 0.21 works in M1
> 

## Steps to Reproduce
1. clone https://github.com/DefiCake/r0_debug_bitcode (if 404 the repo may have moved to private)
1. using an **x86 machine** `cargo b -r` yields:
   ![image](https://github.com/risc0/risc0/assets/35669742/d484e81f-e3b6-4c3a-81dd-289921115eda)
1. using an M1 or other ISA machine `cargo b -r` works fine
1. using **any machine** `cargo b` works

## Expected behavior

If debug build works, release should too!

## Your Environment
- risc0-zkvm version: v0.21
- Rust version: stable-x86_64-unknown-linux-gnu (default) // rustc 1.78.0 (9b00956e5 2024-04-29)
- Platform/OS: Pop_OS! LTS 24 & macOS (? version)

## Additional context

I am betting this is related to something not easy to spot in the release notes on breaking changes and perhaps some API changes and/or what things are named or located?

**Comment by DefiCake** [comment] 2024-06-14 09:07
Hi @nuke-web3 ,

as commented in discord, I think this issue should be closed. We now know that the relay has been deprecated for new versions. We can close this. I have also closed the repository where the issue can be reproduced. Thanks :)

**Closed** 2024-07-16 01:42 UTC
Labels: bug

**Comment by aditya2499** [comment] 2025-02-17 16:09
Hi, @nuke-web3  and @DefiCake , I am having the same issue with risc0-zkvm version v1.2.1 upgrading from v1.1.1.
The Discord link mentioned in the post is not working for me, showing nothing.

Can you share the solution that works for this issue? May be the same fix, works for me too.

Thanks!
