### ISSUE TITLE
[BUG] unix/cmath.rs does not exist

### ISSUE THREAD

**Issue by marijanp** [risc0/risc0#1647] opened 2024-04-09 14:40 UTC
## Bug Report
When building rust-src for the `riscv32im-risc0-zkvm-elf` target I get a file not found error due to this wrong path:
- master: https://github.com/rust-lang/rust/blob/ff24ef91fc848832a8dab483d3b17097cbead5a8/library/std/src/sys/pal/zkvm/mod.rs#L15
- tag 1.77.1: https://github.com/rust-lang/rust/blob/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/sys/pal/zkvm/mod.rs#L15

`cmath.rs` is not located in the `unix` directory, rather in the `sys` directory at the same level as `pal` here:
- master : https://github.com/rust-lang/rust/blob/master/library/std/src/sys/cmath.rs
- tag 1.77.1: https://github.com/rust-lang/rust/tree/1.77.1/library/std/src/sys/cmath

## Steps to Reproduce
1. Fetch the template
2. go to methods/guest
3. run `cargo build -Z build-std --target riscv32im-risc0-zkvm-elf`
```
error: couldn't read /nix/store/mhzd2fna42zfxdpdn0kr1zcnmrcck17p-rust-default-1.77.1/lib/rustlib/src/rust/library/std/src/sys/pal/zkvm/../unix/cmath.rs: No such file or directory (os error 2)
  --> /nix/store/mhzd2fna42zfxdpdn0kr1zcnmrcck17p-rust-default-1.77.1/lib/rustlib/src/rust/library/std/src/sys/pal/zkvm/mod.rs:16:1
   |
16 | pub mod cmath;
```

## Your Environment
- risc0-zkvm version: 0.21.0
- Rust version: 1.77.1
- Platform/OS: Linux

**Comment by marijanp** [comment] 2024-04-12 15:53
I craeted a PR, I wonder whether it would be better to remove all the relative paths https://github.com/rust-lang/rust/pull/123858

**Comment by SchmErik** [comment] 2024-04-15 15:47
Thanks for the report: I actually have a patch that addresses this. I see you fixed the cmath thing but there's another one so I'll follow up with that

**Comment by marijanp** [comment] 2024-04-15 16:50
@SchmErik how do you keep track of regressions for the zkvm target?

**Comment by SchmErik** [comment] 2024-04-15 19:13
we maintain a fork of the upstream rust repo and once upstream releases, I update our fork to build the rust binaries and deal with regressions then. There are much better way of finding regressions than my current process though. Since my patch got merged, I'm going to close this. Thanks for the report!

**Closed by SchmErik** 2024-04-15 19:13 UTC
Labels: bug
