### ISSUE TITLE
note: the lang item is first defined in crate `std` (which `serde` depends on)

### ISSUE THREAD

**Issue by GopherJ** [risc0/risc0#1075] opened 2023-11-01 13:23 UTC
```toml
[dependencies]
pxp-primitives = { path = "../../primitives", default-features = false, features = [] }
risc0-zkvm     = { version = "0.18", default-features = false, features = [] }

[patch.crates-io]
radium = { git = 'https://github.com/ferrilab/radium.git', rev = "723bed5" }
# use optimized risc0 circuit
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.2-risczero.0" }
k256          = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.1-risczero.1" }
sha2          = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.6-risczero.0" }

[features]
default = []
std     = ["pxp-primitives/std", "risc0-zkvm/std"]

```

I try to use no_std of risc0-zkvm, my own crate implemented no_std as well but it paniced

**Comment by GopherJ** [comment] 2023-11-01 13:26
FYI, I'm using v0.18.0

**Comment by GopherJ** [comment] 2023-11-08 16:53
```
pxp-block: Starting build for riscv32im-risc0-zkvm-elfprimitives, pxp-guest(build), pxp-primitives(test)
pxp-block:    Compiling pxp-primitives v0.1.0 (/home/cj/Projects/parax-perpetual/primitives)
pxp-block:    Compiling risc0-zkvm v0.19.0
pxp-block: error[E0152]: found duplicate lang item `panic_impl`
pxp-block:    --> /home/cj/.cargo/registry/src/index.crates.io-6f17d22bba15001f/risc0-zkvm-0.19.0/src/guest/mod.rs:188:1
pxp-block:     |
pxp-block: 188 | fn panic_impl(panic_info: &core::panic::PanicInfo) -> ! {
pxp-block:     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pxp-block:     |
pxp-block:     = note: the lang item is first defined in crate `std` (which `getrandom` depends on)
pxp-block:     = note: first definition in `std` loaded from /home/cj/.local/share/cargo-risczero/toolchains/x86_64-unknown-linux-gnu_test-release-2/rust/lib/rustlib/riscv32im-risc0-zkvm-elf/lib/libstd-4e8651e6ad4e42bb.rlib
pxp-block:     = note: second definition in the local crate (`risc0_zkvm`)
pxp-block:
pxp-block: For more information about this error, try `rustc --explain E0152`.
pxp-block: error: could not compile `risc0-zkvm` (lib) due to previous error
pxp-block: warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `pxp-guest v0.1.0 (/home/cj/Projects/parax-perpetual/guest)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_DEV_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.


```

**Comment by flaub** [comment] 2023-11-08 20:39
Some crates depend on `std` and when this happens you need to use:
```
risc0-zkvm     = { version = "0.18", default-features = false, features = ["std"] }
```

**Comment by GopherJ** [comment] 2023-11-09 01:21
@flaub do you mean my crate or risc0-zkvm ?

**Comment by flaub** [comment] 2023-11-09 03:25
As soon as any crate in your entire dependency graph depends on `std`, then this requires all crates to support `std`, including `risc0-zkvm`. The issue is that when any crate that you use on the guest uses `std`, it means our no-std support will conflict, as you're seeing with duplicate lang items.

**Comment by GopherJ** [comment] 2023-11-09 03:37
ok then I think it's caused by ethers-core

**Comment by flaub** [comment] 2023-11-09 04:02
Closing this for now since it doesn't appear to be an issue we can fix on our end.

**Closed by flaub** 2023-11-09 04:02 UTC
