### ISSUE TITLE
[Documentation]: Website Access Issue: Connection Timeout Error on risczero.com

### ISSUE THREAD

**Issue by 0xBitzz** [risc0/risc0#1889] opened 2024-05-25 11:08 UTC
## User's Objective

As a user reading the documentation, I want to access the Risc Zero website without encountering connection errors, ensuring that all links in the documentation work correctly.

## User's Obstacle

Currently, accessing the Risc Zero website via `https://risczero.com`, which is in the docs and the GitHub organization, results in a connection timeout error:
```
The connection has timed out
An error occurred during a connection to risczero.com.
```
However, the website loads correctly when accessed via `https://www.risczero.com`.

## User's Request

I suggest updating the website configuration to ensure that both `https://risczero.com` and `https://www.risczero.com` work seamlessly. Here are two potential solutions:

### Temporary Solution
For now, update all the documentation and links to use `https://www.risczero.com` instead of `https://risczero.com`.

### Permanent Solution
Implement a permanent fix by configuring redirects on the web server.

Implementing these changes will ensure that users can access the Risc Zero website without encountering connection errors, improving the overall user experience.

**Comment by nuke-web3** [comment] 2024-05-29 23:35
Strange @0xBitzz I cannot reproduce this now. What are you doing to trigger this? what browser and OS are you using? can you share the console logs? 

It might have been a simple blip and is resolved in the DNS system now...?

**Closed** 2024-05-29 23:42 UTC
Labels: documentation
