### ISSUE TITLE
receipt.jorunal

### ISSUE THREAD

**Issue by Peponks9** [risc0/risc0#951] opened 2023-10-05 04:51 UTC
I was following the "Hello world" tutorial to play around with risczero (at https://github.com/risc0/risc0/blob/main/examples/hello-world/tutorial.md#load-values-from-the-host) and when I got to the line where we extract the journal of receipt

`let c: u64 = from_slice(&receipt.journal).unwrap();`

after `&receipt.`, when i start typing the letter 'j' for journal i automatically get 'jorunal' as default leading to errors when compiling or going forward needing to type it manually. I recall it doesn't happen for other methods. Hope it makes sense and doesn't happen just to me.

**Comment by SchmErik** [comment] 2023-10-16 23:01
A lot of auto completion mechanisms scan the code that you're writing to make guesses as to what you're trying to type. This is likely caused by the word `journal` being miss spelled as 'jorunal' somewhere in your code and is not related to any code within our repo. Another suggestion would be to use vscode's rust analyzer extension that might give you a better auto completion https://marketplace.visualstudio.com/items?itemName=rust-lang.rust-analyzer Anyway, we'll close this as this is not specific to our codebase

**Closed** 2023-10-16 23:02 UTC
